USE SISTEMA;
DELIMITER //
	CREATE PROCEDURE RETORNAR_PESSOAS()
	BEGIN
        SELECT * FROM PES_PESSOAS;
    END //
DELIMITER ;

DELIMITER //
	CREATE PROCEDURE PROCURAR_USUARIO(IN VUSU_SENHA VARCHAR(150), IN VUSU_EMAIL VARCHAR(150))
    BEGIN
		SELECT * FROM USU_USUARIO USU
        INNER JOIN PES_PESSOAS PES ON PES.PES_ID = USU.PES_ID
        INNER JOIN ALU_ALUNOS ALU ON ALU.USU_ID = USU.USU_ID
        WHERE 
			USU.USU_SENHA = VUSU_SENHA 
		AND USU.USU_EMAIL = VUSU_EMAIL;
    END //
DELIMITER ;

DELIMITER //
	CREATE PROCEDURE BUSCAR_ALUNOS()
	BEGIN

SELECT 
	USU.USU_ID,
	PES.PES_NOME,
	ALU.ALU_RA,
	ALU.ALU_DATA_VESTIBULAR,
	USU.USU_EMAIL
FROM ALU_ALUNOS ALU
INNER JOIN USU_USUARIO USU ON USU.USU_ID = ALU.USU_ID
INNER JOIN PES_PESSOAS PES ON PES.PES_ID = USU.PES_ID ;

END //
DELIMITER ;

DELIMITER //
	CREATE PROCEDURE INSERIR_VALORES (IN NOME_PESSOA VARCHAR(150), IN DATA_NASCI_PESSOA DATETIME,  
	IN EMAIL_USUARIO VARCHAR(150), IN SENHA_USUARIO VARCHAR(150), IN RA_ALUNO INT, IN DATA_VEST_ALUNO DATETIME)

	BEGIN 	
    
    DECLARE VPES_ID INT;
    DECLARE VUSU_ID INT;
	DECLARE ERRO INT DEFAULT 0;
    DECLARE CONTINUE HANDLER FOR SQLEXCEPTION SET ERRO = 1;
    
    START TRANSACTION;
	
    INSERT INTO PES_PESSOAS (PES_NOME, PES_DATA_NASCIMENTO) VALUES(NOME_PESSOA, DATA_NASCI_PESSOA);
	IF ERRO = 1 THEN		
        SELECT "-1" AS ERRO;
      ROLLBACK;
	 ELSE
		SET VPES_ID = (LAST_INSERT_ID()); 
		INSERT INTO USU_USUARIO (USU_EMAIL, USU_DATA_CADASTRO, USU_SENHA, PES_ID)
		VALUES 
		(EMAIL_USUARIO, sysdate(), SENHA_USUARIO, VPES_ID);
		IF ERRO = 1 THEN		
        SELECT "-1" AS ERRO;
			ROLLBACK;
		ELSE
        
			SET VUSU_ID = (LAST_INSERT_ID());
			INSERT INTO ALU_ALUNOS (ALU_RA, ALU_DATA_VESTIBULAR, USU_ID)
			VALUES  
			(RA_ALUNO, DATA_VEST_ALUNO, VUSU_ID); 
            IF ERRO = 1 THEN		
				SELECT "-1" AS ERRO;
				ROLLBACK;
			ELSE
				SELECT "0" AS ERRO;
                COMMIT;
            END IF;
        END IF;
	END IF;
END // 
DELIMITER ;

DELIMITER //
	CREATE PROCEDURE BUSCAR_PERFIL(IN VUSU_ID INT)
	BEGIN
SELECT 
	ALU.ALU_RA,
	USU.USU_EMAIL,
	PES.PES_NOME
FROM ALU_ALUNOS ALU
INNER JOIN USU_USUARIO USU ON USU.USU_ID = ALU.USU_ID
INNER JOIN PES_PESSOAS PES ON PES.PES_ID = USU.PES_ID 
WHERE USU.USU_ID = VUSU_ID;

END //
DELIMITER ;

DELIMITER //
	CREATE PROCEDURE EXCLUIR(IN VRA INT)
    BEGIN
		DECLARE VPES_ID INT;
		DECLARE VUSU_ID INT;
		DECLARE VALU_RA INT;
        
        START TRANSACTION;

		SET VALU_RA = VRA;
        SET VUSU_ID = (SELECT USU_ID FROM ALU_ALUNOS WHERE ALU_RA = VALU_RA);
        SET VPES_ID = (SELECT PES_ID FROM USU_USUARIO WHERE USU_ID = VUSU_ID);
        
        DELETE FROM ALU_ALUNOS 	WHERE ALU_RA = VALU_RA;
        DELETE FROM USU_USUARIO WHERE USU_ID = VUSU_ID;
        DELETE FROM PES_PESSOAS WHERE PES_ID = VPES_ID;
        COMMIT;
    END //
DELIMITER ;

CALL INSERIR_VALORES ('admin', '0001-01-01', 'admin@gmail.com', 'admin', 1, '0001-01-01');



