CREATE DATABASE SISTEMA;
USE SISTEMA;
-- CRIAÇÃO DAS TABELAS 
-- TABELA DE PESSOAS
CREATE TABLE PES_PESSOAS(
    PES_ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    PES_NOME VARCHAR(150) NOT NULL,
    PES_DATA_NASCIMENTO DATETIME NOT NULL
);

-- TABELA DE USUARIO
CREATE TABLE USU_USUARIO(
	USU_ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    USU_EMAIL VARCHAR(150) NOT NULL,
    USU_DATA_CADASTRO DATETIME NOT NULL,
    USU_SENHA VARCHAR(150) NOT NULL,
	PES_ID INT NOT NULL,
    FOREIGN KEY (PES_ID) REFERENCES PES_PESSOAS(PES_ID)
);

-- TABELA DE ALUNOSRETORNAR_PESSOASPROCURAR_USUARIO
CREATE TABLE ALU_ALUNOS(
	ALU_RA INT PRIMARY KEY NOT NULL,
    ALU_DATA_VESTIBULAR DATETIME NOT NULL,
    USU_ID INT NOT NULL,
    FOREIGN KEY (USU_ID) REFERENCES USU_USUARIO(USU_ID)
);